<?php

return [
    'provinces' => array (
  0 => 'Aceh',
  1 => 'Bali',
  2 => 'Banten',
  3 => 'Bengkulu',
  4 => 'DKI Jakarta',
  5 => 'Daerah Istimewa Yogyakarta',
  6 => 'Gorontalo',
  7 => 'Jambi',
  8 => 'Jawa Barat',
  9 => 'Jawa Tengah',
  10 => 'Jawa Timur',
  11 => 'Kalimantan Barat',
  12 => 'Kalimantan Selatan',
  13 => 'Kalimantan Tengah',
  14 => 'Kalimantan Timur',
  15 => 'Kalimantan Utara',
  16 => 'Kepulauan Bangka Belitung',
  17 => 'Kepulauan Riau',
  18 => 'Lampung',
  19 => 'Maluku',
  20 => 'Maluku Utara',
  21 => 'Nusa Tenggara Barat',
  22 => 'Nusa Tenggara Timur',
  23 => 'Papua',
  24 => 'Papua Barat',
  25 => 'Riau',
  26 => 'Sulawesi Barat',
  27 => 'Sulawesi Selatan',
  28 => 'Sulawesi Tengah',
  29 => 'Sulawesi Tenggara',
  30 => 'Sulawesi Utara',
  31 => 'Sumatera Barat',
  32 => 'Sumatera Selatan',
  33 => 'Sumatera Utara',
),
];
