<?php

// File ini dihasilkan oleh tools/generate_wilayah.py.
// Jangan diedit manual - jalankan ulang generator bila master Excel berubah.

return [
    'provinces' => [
        'Aceh',
        'Bali',
        'Banten',
        'Bengkulu',
        'Gorontalo',
        'Jakarta',
        'Jambi',
        'Jawa Barat',
        'Jawa Tengah',
        'Jawa Timur',
        'Kalimantan Barat',
        'Kalimantan Selatan',
        'Kalimantan Tengah',
        'Kalimantan Timur',
        'Kalimantan Utara',
        'Kepulauan Bangka Belitung',
        'Kepulauan Riau',
        'Lampung',
        'Maluku',
        'Maluku Utara',
        'Nusa Tenggara Barat',
        'Nusa Tenggara Timur',
        'Papua',
        'Papua Barat',
        'Papua Barat Daya',
        'Papua Pegunungan',
        'Papua Selatan',
        'Papua Tengah',
        'Riau',
        'Sulawesi Barat',
        'Sulawesi Selatan',
        'Sulawesi Tengah',
        'Sulawesi Tenggara',
        'Sulawesi Utara',
        'Sumatera Barat',
        'Sumatera Selatan',
        'Sumatera Utara',
        'Yogyakarta',
    ],
];
